// flow-typed signature: e907e5ce2566dabbdc9cae135ea676a0
// flow-typed version: <<STUB>>/mdn-polyfills_v5.20.x/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mdn-polyfills'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mdn-polyfills' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mdn-polyfills/Array.from' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.of' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.fill' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.filter' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.find' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.findIndex' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.forEach' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.includes' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.reduce' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Array.prototype.some' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/CustomEvent' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Element.prototype.classList' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Element.prototype.closest' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Element.prototype.getAttributeNames' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Element.prototype.matches' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Element.prototype.toggleAttribute' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Function.prototype.bind' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/HTMLCanvasElement.prototype.toBlob' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/MouseEvent' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.addEventListener' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.after' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.append' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.before' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.children' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.firstElementChild' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.prepend' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.remove' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Node.prototype.replaceWith' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/NodeList.prototype.forEach' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Number.isInteger' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Number.isNaN' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Object.assign' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Object.create' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Object.entries' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Object.keys' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/Object.values' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/String.prototype.endsWith' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/String.prototype.includes' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/String.prototype.padEnd' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/String.prototype.padStart' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/String.prototype.repeat' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/String.prototype.startsWith' {
  declare module.exports: any;
}

declare module 'mdn-polyfills/String.prototype.trim' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mdn-polyfills/Array.from.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.from'>;
}
declare module 'mdn-polyfills/Array.of.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.of'>;
}
declare module 'mdn-polyfills/Array.prototype.fill.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.fill'>;
}
declare module 'mdn-polyfills/Array.prototype.filter.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.filter'>;
}
declare module 'mdn-polyfills/Array.prototype.find.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.find'>;
}
declare module 'mdn-polyfills/Array.prototype.findIndex.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.findIndex'>;
}
declare module 'mdn-polyfills/Array.prototype.forEach.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.forEach'>;
}
declare module 'mdn-polyfills/Array.prototype.includes.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.includes'>;
}
declare module 'mdn-polyfills/Array.prototype.reduce.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.reduce'>;
}
declare module 'mdn-polyfills/Array.prototype.some.js' {
  declare module.exports: $Exports<'mdn-polyfills/Array.prototype.some'>;
}
declare module 'mdn-polyfills/CustomEvent.js' {
  declare module.exports: $Exports<'mdn-polyfills/CustomEvent'>;
}
declare module 'mdn-polyfills/Element.prototype.classList.js' {
  declare module.exports: $Exports<'mdn-polyfills/Element.prototype.classList'>;
}
declare module 'mdn-polyfills/Element.prototype.closest.js' {
  declare module.exports: $Exports<'mdn-polyfills/Element.prototype.closest'>;
}
declare module 'mdn-polyfills/Element.prototype.getAttributeNames.js' {
  declare module.exports: $Exports<'mdn-polyfills/Element.prototype.getAttributeNames'>;
}
declare module 'mdn-polyfills/Element.prototype.matches.js' {
  declare module.exports: $Exports<'mdn-polyfills/Element.prototype.matches'>;
}
declare module 'mdn-polyfills/Element.prototype.toggleAttribute.js' {
  declare module.exports: $Exports<'mdn-polyfills/Element.prototype.toggleAttribute'>;
}
declare module 'mdn-polyfills/Function.prototype.bind.js' {
  declare module.exports: $Exports<'mdn-polyfills/Function.prototype.bind'>;
}
declare module 'mdn-polyfills/HTMLCanvasElement.prototype.toBlob.js' {
  declare module.exports: $Exports<'mdn-polyfills/HTMLCanvasElement.prototype.toBlob'>;
}
declare module 'mdn-polyfills/MouseEvent.js' {
  declare module.exports: $Exports<'mdn-polyfills/MouseEvent'>;
}
declare module 'mdn-polyfills/Node.prototype.addEventListener.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.addEventListener'>;
}
declare module 'mdn-polyfills/Node.prototype.after.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.after'>;
}
declare module 'mdn-polyfills/Node.prototype.append.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.append'>;
}
declare module 'mdn-polyfills/Node.prototype.before.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.before'>;
}
declare module 'mdn-polyfills/Node.prototype.children.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.children'>;
}
declare module 'mdn-polyfills/Node.prototype.firstElementChild.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.firstElementChild'>;
}
declare module 'mdn-polyfills/Node.prototype.prepend.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.prepend'>;
}
declare module 'mdn-polyfills/Node.prototype.remove.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.remove'>;
}
declare module 'mdn-polyfills/Node.prototype.replaceWith.js' {
  declare module.exports: $Exports<'mdn-polyfills/Node.prototype.replaceWith'>;
}
declare module 'mdn-polyfills/NodeList.prototype.forEach.js' {
  declare module.exports: $Exports<'mdn-polyfills/NodeList.prototype.forEach'>;
}
declare module 'mdn-polyfills/Number.isInteger.js' {
  declare module.exports: $Exports<'mdn-polyfills/Number.isInteger'>;
}
declare module 'mdn-polyfills/Number.isNaN.js' {
  declare module.exports: $Exports<'mdn-polyfills/Number.isNaN'>;
}
declare module 'mdn-polyfills/Object.assign.js' {
  declare module.exports: $Exports<'mdn-polyfills/Object.assign'>;
}
declare module 'mdn-polyfills/Object.create.js' {
  declare module.exports: $Exports<'mdn-polyfills/Object.create'>;
}
declare module 'mdn-polyfills/Object.entries.js' {
  declare module.exports: $Exports<'mdn-polyfills/Object.entries'>;
}
declare module 'mdn-polyfills/Object.keys.js' {
  declare module.exports: $Exports<'mdn-polyfills/Object.keys'>;
}
declare module 'mdn-polyfills/Object.values.js' {
  declare module.exports: $Exports<'mdn-polyfills/Object.values'>;
}
declare module 'mdn-polyfills/String.prototype.endsWith.js' {
  declare module.exports: $Exports<'mdn-polyfills/String.prototype.endsWith'>;
}
declare module 'mdn-polyfills/String.prototype.includes.js' {
  declare module.exports: $Exports<'mdn-polyfills/String.prototype.includes'>;
}
declare module 'mdn-polyfills/String.prototype.padEnd.js' {
  declare module.exports: $Exports<'mdn-polyfills/String.prototype.padEnd'>;
}
declare module 'mdn-polyfills/String.prototype.padStart.js' {
  declare module.exports: $Exports<'mdn-polyfills/String.prototype.padStart'>;
}
declare module 'mdn-polyfills/String.prototype.repeat.js' {
  declare module.exports: $Exports<'mdn-polyfills/String.prototype.repeat'>;
}
declare module 'mdn-polyfills/String.prototype.startsWith.js' {
  declare module.exports: $Exports<'mdn-polyfills/String.prototype.startsWith'>;
}
declare module 'mdn-polyfills/String.prototype.trim.js' {
  declare module.exports: $Exports<'mdn-polyfills/String.prototype.trim'>;
}
